spring.application.name=hospital_management_system

# Dynamic Port assigned by Cloud Server (defaults to 8080 locally)
server.port=${PORT:8080}

# Cloud Database URL / Credentials (defaults to your local Postgres)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hospital_data}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Hibernate JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
